remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: perfo
description: the perfo website
url: https://perfo-github.github.io/website
show_downloads: false

links:
  - name:         perfo  
    url:          </index.md>
    external:     false
  - name:         requirements
    url:          <./requirements to be perfo.html>
    external:     false
  - name:         how perfo apps are made
    url:          <./how perfo apps are made.html>
    external:     false
  - name:         perfo extended
    url:          <./perfo extended.html>
    external:     false